apiVersion: 3
dataDisplay:
  excludedFeatures: []
  noneValues:
  - none
  - unknown
  - null
  - NA
  sectionSep1: '@'
  textFormat: text-orig-full
interfaceDefaults:
  fmt: text-orig-full
provenanceSpec:
  branch: main
  corpus: 'UBS GNT5 (converted from Emdros)'
  doi: 10.5281/zenodo.notyet
  moduleSpecs: []
  version: 0.0.1
  webBase: https://public.{org}.org/{repo}
  webHint: Show this on the website
  webLang: en
  webUrl: '{webBase}/<1>/<2>/<3>&version={version}'
  webUrlLex: '{webBase}/word?version={version}&id=<lid>'
typeDisplay:
  word:
    featuresBare: surface
writing: grc
